apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment-{{ .Values.env }}
  labels:
    app: mongo
    env: {{ .Values.env }}
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "webapp-deployment-{{ .Values.env }}"
    meta.helm.sh/release-namespace: "default"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: mongo
        env: {{ .Values.env }}
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret-{{ .Values.env }}
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret-{{ .Values.env }}
              key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service-{{ .Values.env }}
  labels:
    env: {{ .Values.env }}
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "webapp-deployment-{{ .Values.env }}"
    meta.helm.sh/release-namespace: "default"
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017