apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webapp-monitor-{{ .Values.env }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: webapp-deployment-{{ .Values.env }}
  endpoints:
  - port: metrics
    interval: 30s