apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-post-upgrade-script
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/resource-policy": keep
    "helm.sh/hook-delete-policy": hook-succeeded
data:
  notify.sh: |
    #!/bin/sh
    curl -i -X POST -H 'Content-Type: application/json' -d "{\"text\": \"webapp-$1 version $2 is deployed to Kubernetes! :tada:\"}" https://hooks.slack.com/services/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